### ISSUE TITLE
badge 생성을 위한 userinfo 던져주는 기능

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/rankit-be#182]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!
badge 생성을 위한 userinfo 던져주는 기능

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] controller, service, responseDto 작성
- [x] test

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!

**Comment by khyojun** [comment]
완료되어서 이슈 닫을게요~
